import { useCallback, useState } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';

import { Background, Button, Header, FormationCard } from '@/components';

const formationData = [
  {
    name: '4 - 4 - 2',
    attack: 80,
    defence: 75,
    middle: 50,
    image: '/formations/formation-a.svg'
  },
  {
    name: '4 - 3 - 3',
    attack: 60,
    defence: 75,
    middle: 60,
    image: '/formations/formation-b.svg'
  },
  {
    name: '4 - 5 - 1',
    attack: 40,
    defence: 70,
    middle: 75,
    image: '/formations/formation-c.svg'
  },
  {
    name: '5 - 3 - 2',
    attack: 60,
    defence: 80,
    middle: 60,
    image: '/formations/formation-d.svg'
  }
];

export default function Formation() {
  const [selectedFormation, setSelectedFormation] = useState(0);
  const router = useRouter();

  const handleFormationChangeCallback = useCallback(
    (formationId: number) => setSelectedFormation(formationId),
    []
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Formation screen */}

      {/* Background component */}
      <Background image="/backgrounds/stadium-screen.svg" blur />

      {/* Header component */}
      <Header title="Choose a Formation" backButton />

      <div className="formation-view">
        {/* Formations section */}
        <section className="formation-section">
          {formationData.map((form, idx) => {
            const isSelected = selectedFormation === idx;
            return (
              <FormationCard
                key={form.name}
                {...form}
                isSelected={isSelected}
                onClickCallback={() => handleFormationChangeCallback(idx)}
              />
            );
          })}
        </section>

        {/* Ready Button component */}
        <Button size="large" onClick={() => router.push('/versus')}>
          Ready
        </Button>
      </div>
    </>
  );
}
