/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';

import { Background, Button, Icon, Navigation } from '../components';
import ControllerButton from '../components/ControllerButton/ControllerButton';
const navLinks = [
  {
    href: '/friends',
    text: 'friends',
    icon: <Icon name="friends" />
  },
  {
    href: '/facilities',
    text: 'facilities',
    icon: <Icon name="facilities" />
  },
  {
    href: '/team',
    text: 'team',
    icon: <Icon name="friends" />
  },
  {
    href: '/collection',
    text: 'collection',
    icon: <Icon name="collection" />
  },
  {
    href: '/market',
    text: 'market',
    icon: <Icon name="market" />
  }
];

export default function Home() {
  const router = useRouter();
  const goToQuickMatch = () => router.push('/quick-match');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main menu screen */}

      {/* Background component */}
      <Background image="/backgrounds/stadium-screen.svg" blur />

      {/* Overlay component */}
      <div
        className="overlay"
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-evenly',
          zIndex: 1000,
          position: 'absolute',
          width: '100%',
          height: '100%'
        }}
      >
        <div>
          <img src="/mocks/stadium.png" alt="field" height={200} />
        </div>
        <div className="overlay-centre">
          <p className="title">
            <Image src="/text/zokker.png" alt="Zokker logo" height={151} width={710} />
          </p>
          <div className="button-group">
            <Button>Leagues</Button>
            <Button size="large" onClick={goToQuickMatch}>
              Quick Match
            </Button>
            <Button>Training</Button>
          </div>
        </div>
        <div>
          <img src="/mocks/team-panel.png" alt="team" height={400} />
        </div>
      </div>

      {/* Navigation component */}
      <Navigation links={navLinks} />

      {/* Connect Button */}
      <div className="flex gap-2 mb-4">
        <button
          className="px-4 py-2 bg-blue-600 text-white text-sm sm:text-base rounded-md hover:bg-blue-700 transition-colors duration-300"
          // onClick={() => account?.create()}
        >
          {/* {account?.isDeploying ? 'Deploying Burner...' : 'Create Burner'} */}a
        </button>
        <ControllerButton />
      </div>
    </>
  );
}
